repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
    -   id: check-merge-conflict
    -   id: check-toml
    -   id: check-yaml
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.5.5
  hooks:
    - id: ruff
      args: [ --fix, --unsafe-fixes, --exit-non-zero-on-fix ]
    - id: ruff-format
      types_or: [ python, pyi, jupyter]

- repo: https://github.com/MarcoGorelli/madforhooks
  rev: 0.4.1
  hooks:
    - id: no-print-statements
      files: ^better_optimize/
      exclude: ^better_optimize/_version\.py$
