from typing import Literal

minimize_method = Literal[
    "nelder-mead",
    "powell",
    "CG",
    "BFGS",
    "Newton-CG",
    "L-BFGS-B",
    "TNC",
    "COBYLA",
    "SLSQP",
    "trust-constr",
    "dogleg",
    "trust-ncg",
    "trust-exact",
    "trust-krylov",
]

root_method = Literal[
    "hybr",
    "lm",
    "broyden1",
    "broyden2",
    "anderson",
    "linearmixing",
    "diagbroyden",
    "excitingmixing",
    "krylov",
    "df-sane",
]

TOLERANCES = ["xtol", "ftol", "gtol", "fatol", "xatol"]
CONSOLE_WIDTH = 100

DE_STRATEGY_OPTIONS = (
    "best1bin",
    "best1exp",
    "rand1bin",
    "rand1exp",
    "randtobest1bin",
    "randtobest1exp",
    "currenttobest1bin",
    "currenttobest1exp",
    "best2bin",
    "best2exp",
    "rand2bin",
    "rand2exp",
)

DE_INIT_OPTIONS = ("sobol", "halton", "latinhypercube", "random")

# SciPy's direct solvers ignore the callback argument; the iterative root finders honor it.
ROOT_METHODS_WITHOUT_CALLBACK = frozenset({"hybr", "lm"})


ROOT_MODE_KWARGS = {
    "hybr": {
        "uses_jac": True,
        "f_maxiter_default": lambda n: 100 * (n + 1),
        "valid_options": ["col_deriv", "xtol", "maxfev", "band", "eps", "factor", "diag"],
    },
    "lm": {
        "uses_jac": True,
        "f_maxiter_default": lambda n: 100 * (n + 1),
        "valid_options": ["col_deriv", "ftol", "xtol", "gtol", "maxiter", "eps", "factor", "diag"],
    },
    "broyden1": {
        "uses_jac": False,
        "f_maxiter_default": lambda n: 100 * (n + 1),
        "valid_options": [
            "nit",
            "disp",
            "maxiter",
            "ftol",
            "fatol",
            "xtol",
            "xatol",
            "tol_norm",
            "line_search",
            "max_rank",
            "jac_options",
        ],
        "jac_options": ["alpha", "reduction_method", "to_retain"],
    },
    "broyden2": {
        "uses_jac": False,
        "f_maxiter_default": lambda n: 100 * (n + 1),
        "valid_options": [
            "nit",
            "disp",
            "maxiter",
            "ftol",
            "fatol",
            "xtol",
            "xatol",
            "tol_norm",
            "line_search",
            "max_rank",
            "jac_options",
        ],
        "jac_options": ["alpha", "reduction_method", "to_retain"],
    },
    "anderson": {
        "uses_jac": False,
        "f_maxiter_default": lambda n: 100 * (n + 1),
        "valid_options": [
            "nit",
            "disp",
            "maxiter",
            "ftol",
            "fatol",
            "xtol",
            "xatol",
            "tol_norm",
            "line_search",
            "jac_options",
        ],
        "jac_options": ["alpha", "M", "w0"],
    },
    "linearmixing": {
        "uses_jac": False,
        "f_maxiter_default": lambda n: 100 * (n + 1),
        "valid_options": [
            "nit",
            "disp",
            "maxiter",
            "ftol",
            "fatol",
            "xtol",
            "xatol",
            "tol_norm",
            "line_search",
            "jac_options",
        ],
        "jac_options": ["alpha"],
    },
    "diagbroyden": {
        "uses_jac": False,
        "f_maxiter_default": lambda n: 100 * (n + 1),
        "valid_options": [
            "nit",
            "disp",
            "maxiter",
            "ftol",
            "fatol",
            "xtol",
            "xatol",
            "tol_norm",
            "line_search",
            "jac_options",
        ],
        "jac_options": ["alpha"],
    },
    "excitingmixing": {
        "uses_jac": False,
        "f_maxiter_default": lambda n: 100 * (n + 1),
        "valid_options": [
            "nit",
            "disp",
            "maxiter",
            "ftol",
            "fatol",
            "xtol",
            "xatol",
            "tol_norm",
            "line_search",
            "jac_options",
        ],
        "jac_options": ["alpha", "alphamax"],
    },
    "krylov": {
        "uses_jac": False,
        "f_maxiter_default": lambda n: 100 * (n + 1),
        "valid_options": [
            "nit",
            "disp",
            "maxiter",
            "ftol",
            "fatol",
            "xtol",
            "xatol",
            "tol_norm",
            "line_search",
            "jac_options",
        ],
        "jac_options": [
            "rdiff",
            "method",
            "inner_M",
            "inner_tol",
            "inner_maxiter",
            "outer_k",
        ],
    },
    "df-sane": {
        "uses_jac": False,
        "f_maxiter_default": lambda n: 100 * (n + 1),
        "valid_options": [
            "ftol",
            "fatol",
            "fnorm",
            "maxfev",
            "disp",
            "eta_strategy",
            "sigma_eps",
            "sigma_0",
            "M",
            "line_search",
        ],
    },
}
