name: release-pipeline

on:
  release:
    types:
      - created

jobs:
  release-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install release tooling
        run: |
          pip install twine wheel
      - name: Build package
        run: |
          python setup.py sdist bdist_wheel
      - name: Check version number match
        run: |
          echo "GITHUB_REF: ${GITHUB_REF}"
          # The GITHUB_REF should be something like "refs/tags/v1.2.3"
          # Make sure the package version is the same as the tag
          grep -Rq "^Version: ${GITHUB_REF:11}$" better_optimize.egg-info/PKG-INFO
  pypi-publish:
    needs: release-job
    name: upload release to PyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
  test-install-job:
    needs: pypi-publish
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.7
    - name: Give PyPI a chance to update the index
      run: sleep 240
    - name: Install from PyPI
      run: |
        pip install better_optimize==${GITHUB_REF:11}
